"""add change name Pagos column id_cuota to id_item

Revision ID: 0f857217201e
Revises: 7ea5cbc9581a
Create Date: 2026-07-21 22:56:10.206491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f857217201e'
down_revision: Union[str, Sequence[str], None] = '7ea5cbc9581a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos', sa.Column('id_item', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_pagos_id_cuota'), table_name='pagos')
    op.create_index(op.f('ix_pagos_id_item'), 'pagos', ['id_item'], unique=False)
    op.drop_column('pagos', 'id_cuota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos', sa.Column('id_cuota', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pagos_id_item'), table_name='pagos')
    op.create_index(op.f('ix_pagos_id_cuota'), 'pagos', ['id_cuota'], unique=False)
    op.drop_column('pagos', 'id_item')
    # ### end Alembic commands ###
