"""Crear tabla de pagos

Revision ID: 7ea5cbc9581a
Revises: 
Create Date: 2026-07-14 23:49:55.794765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea5cbc9581a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pago_externo', sa.String(), nullable=False),
    sa.Column('pasarela', sa.String(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('id_cuota', sa.UUID(), nullable=True),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id_cuota'), 'pagos', ['id_cuota'], unique=False)
    op.create_index(op.f('ix_pagos_id_pago_externo'), 'pagos', ['id_pago_externo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id_pago_externo'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id_cuota'), table_name='pagos')
    op.drop_table('pagos')
    # ### end Alembic commands ###
